language: R
dist: bionic
cache: packages

install: 
  # Needs to be done on bionic for now
  - sudo apt update -qq
  # Boost
  - sudo apt install -qq libboost-all-dev
  # Urho3D
  - sudo apt-get install libx11-dev libxrandr-dev libasound2-dev libgl1-mesa-dev
  #- sudo apt-get install libsdl1.2-dev libsdl-image1.2-dev libsdl-mixer1.2-dev libsdl-ttf2.0-dev
  - sudo apt-get install libsdl2-dev

services:
 - xvfb

script: 
  - cd Refactored
  - ./Urho3d.sh
  # Console
  - qmake RosindellEtAl2015Console.pro
  - make
  # Desktop
  - qmake RosindellEtAl2015Desktop.pro
  - make
  - ./RosindellEtAl2015Desktop &
  - sleep 10
  - sudo killall RosindellEtAl2015Desktop
  # Desktop 3D
  - qmake RosindellEtAl2015Desktop3d.pro
  - make
  - ./RosindellEtAl2015Desktop3d &
  - sleep 10
  - sudo killall RosindellEtAl2015Desktop3d
  # Get code coverage
  - ./scripts/get_code_cov.sh
  - codecov

after_success:
  # Codecov
  - bash <(curl -s https://codecov.io/bash)
