sudo: required
language: cpp
compiler: gcc

before_install:
  # C++14
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  # C++14
  - sudo apt-get install -qq g++-5
  # Urho3D
  - sudo apt-get install libx11-dev libxrandr-dev libasound2-dev libgl1-mesa-dev
  - sudo apt-get install libsdl1.2-dev libsdl-image1.2-dev libsdl-mixer1.2-dev libsdl-ttf2.0-dev

addons:
  apt:
    sources:
    - boost-latest
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5
    - libboost1.55-all-dev

# Start virtual X server, from https://docs.travis-ci.com/user/gui-and-headless-browsers/
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script: 
  - cd Refactored
  # Console
  - qmake RosindellEtAl2015Console.pro
  - make
  # Desktop
  - qmake RosindellEtAl2015Desktop.pro
  - make
  - ./RosindellEtAl2015Desktop &
  - sleep 10
  - sudo killall RosindellEtAl2015Desktop
  # Desktop 3D
  - qmake RosindellEtAl2015Desktop3d.pro
  - make
  - ./RosindellEtAl2015Desktop3d &
  - sleep 10
  - sudo killall RosindellEtAl2015Desktop3d
  # Get code coverage
  - ./get_code_cov
  - codecov

after_success:
  # Codecov
  - bash <(curl -s https://codecov.io/bash)